# Generated by Django 5.2.18 on 2026-10-07 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='namn')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='anteckning')),
                ('mortgage_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='bolåneskuld')),
                ('mortgage_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='ränta')),
                ('amortization_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='amortering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=80, verbose_name='typ')),
                ('person', models.CharField(blank=True, max_length=80, verbose_name='person')),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='brutto')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='skatt')),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='netto')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='budgets.plan')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='post')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='kategori')),
                ('person', models.CharField(blank=True, max_length=80, verbose_name='vem')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='belopp')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='anteckning')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('source', models.CharField(choices=[('manual', 'Manuell'), ('mortgage_interest', 'Bolån, ränta'), ('mortgage_amortization', 'Bolån, amortering')], default='manual', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgets.plan')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_plan_name'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'manual'), _negated=True), fields=('plan', 'source'), name='unique_derived_expense'),
        ),
    ]
